### ISSUE TITLE
Packet error when breaking blocks on a dedicated server

### ISSUE THREAD

**Issue by Darkhax** [starforcraft/Did-you-pay-your-taxes#1]
Hey, I was testing out this mod on the SpookyJam server and noticed a packet error any time a player tried to break a block while on a dedicated server. 

Taxes: 0.3.1
NeoForge: 21.1.80

[Server Log](https://github.com/user-attachments/files/17848698/latest.2.1.log)

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/did-you-pay-your-taxes/files/5925626
